[versions]
minecraft = "1.19.4"
yarn = "1.19.4+build.1"
fabric-loader = "0.14.17"
fabric-api = "0.76.0+1.19.4"
fabric-loom = "1.1-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
